- name: Get the env
  group_by:
    key: {{ env }}
 
- name: Execute brew bundle
  command:
    cmd: "brew bundle --file=./files/brew/Brewfile --verbose"
  when:
    env == 'mac'

- name: Set apk packages
  command:
    cmd: 'apk add {{ item }}'
  with_items:
    - "{{ apk_packages }}"
  when:
    env == 'ipad'

- name: git user set
  git_config:
    scope: global
    name: user.name
    value: marronnier-tech

- name: git email set
  git_config:
    scope: global
    name: user.email
    value: "{{ git_email }}"

