- name: Execute brew bundle
  ansible.builtin.command:
    cmd: "brew bundle --file={{ file_path }}/brew/Brewfile --verbose"
  register: brew_bundle
  ignore_errors: yes

- name: output result of brew bundle
  debug:
    msg: "{{ brew_bundle }}"

- name: git user set
  community.general.git_config:
    scope: global
    name: user.name
    value: marronnier-tech

- name: git email set
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ git_email }}"

- name: git push.default set
  community.general.git_config:
    scope: global
    name: push.default
    value: current

- name: make vim directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '1777'
  with_items:
    - ~/.config/nvim
    - ~/.vim/colors
    - ~/.cache/dein

- name: set vim config file
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
    owner: tocchy
    #mode: '1777'
  with_items:
    - { src: '{{ file_path }}/.zshrc', dest: '~/.zshrc' }
    - { src: '{{ file_path }}/vim.d/.vimrc', dest: '~/.vimrc' }
    - { src: '{{ file_path }}/vim.d/dein.toml', dest: '~/dein.toml' }
    - { src: '{{ file_path }}/vim.d/dein_lazy.toml', dest: '~/dein_lazy.toml' }
    - { src: '{{ file_path }}/vim.d/.config/nvim/init.vim', dest: '~/.config/nvim/init.vim' }
    - { src: '{{ file_path }}/python', dest: '~/Documents/python'}
    - { src: '{{ file_path }}/golang', dest: '~/Documents/golang'}
    
- name: pynvim install
  ansible.builtin.command: "python3 -m pip install --user --upgrade pynvim"

- name: set venv
  ansible.builtin.command: 
    cmd: "python3 -m venv atc"
    chdir: ~/Documents/python/atcoder
