- name: git user set
  community.general.git_config:
    scope: global
    name: user.name
    value: marronnier-tech

- name: git email set
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ git_email }}"

- name: git push.default set
  community.general.git_config:
    scope: global
    name: push.default
    value: current

- name: make vim directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '1777'
  with_items:
    - ~/.config/nvim
    - ~/.vim/colors
    - ~/.cache/dein

- name: set vim config file
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
    owner: tocchy
    #mode: '1777'
  with_items:
    - { src: '{{ file_path }}/.zshrc', dest: '~/.zshrc' }
    - { src: '{{ file_path }}/tmux/.tmux.conf', dest: '~/.tmux.conf' }
    - { src: '{{ file_path }}/vim.d/.vimrc', dest: '~/.vimrc' }
    - { src: '{{ file_path }}/vim.d/dein.toml', dest: '~/dein.toml' }
    - { src: '{{ file_path }}/vim.d/dein_lazy.toml', dest: '~/dein_lazy.toml' }
    - { src: '{{ file_path }}/vim.d/.config/nvim/init.vim', dest: '~/.config/nvim/init.vim' }
    - { src: '{{ file_path }}/python', dest: '~/Documents/python'}
    - { src: '{{ file_path }}/golang', dest: '~/Documents/golang'}

- name: set vim swagger tool
  ansible.builtin.copy:
    src: "~/.cache/dein/repos/github.com/xavierchow/vim-swagger-preview/.zshenv"
    dest: "~/.zshenv"
    mode: '1777'

- name: install power line fonts
  ansible.builtin.command:
    cmd: sh install.sh
  args:
    chdir: "{{ file_path }}/vim.d/fonts/"
    
- name: pynvim install
  ansible.builtin.command: "python3 -m pip install --user --upgrade pynvim"

- name: set System Preferences
  community.general.osx_defaults:
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items: "{{ osx_defaults_global }}"

- name: set System Preferences out of global domain
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  with_items: "{{ osx_defaults_domain }}"
