- name: Get the env
  group_by:
    key: "{{ env }}"
 
- name: Execute brew bundle
  command:
    cmd: "brew bundle --file={{ file_path }}/brew/Brewfile --verbose"

- name: git user set
  git_config:
    scope: global
    name: user.name
    value: marronnier-tech

- name: git email set
  git_config:
    scope: global
    name: user.email
    value: "{{ git_email }}"

- name: git push.default set
  git_config:
    scope: global
    name: push.default
    value: current

- name: make vim directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '1777'
  with_items:
    - ~/.config/nvim
    - ~/.vim/colors
    - ~/.cache/dein

- name: set vim config file
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
    owner: tocchy
    #mode: '1777'
  with_items:
    - { src: '{{ file_path }}/.zshrc', dest: '~/.zshrc' }
    - { src: '{{ file_path }}/vim.d/.vimrc', dest: '~/.vimrc' }
    - { src: '{{ file_path }}/vim.d/dein.toml', dest: '~/dein.toml' }
    - { src: '{{ file_path }}/vim.d/dein_lazy.toml', dest: '~/dein_lazy.toml' }
    - { src: '{{ file_path }}/vim.d/.config/nvim/init.vim', dest: '~/.config/nvim/init.vim' }
    - { src: '{{ file_path }}/python', dest: '~/Documents/python'}
    - { src: '{{ file_path }}/golang', dest: '~/Documents/golang'}
    
- name: pynvim install
  command: "python3 -m pip install --user --upgrade pynvim"

