[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    nnoremap <leader>n :NERDTreeFocus<CR>
    nnoremap <C-n> :NERDTree<CR>
'''

[[plugins]]
repo = 'preservim/nerdcommenter'
    
[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    colorscheme jellybeans
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
    let g:airline_theme = 'jellybeans'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''

[[plugins]]
repo = 'xavierchow/vim-swagger-preview'
